# Generated by Django 3.1 on 2020-10-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoLinks',
            new_name='VideoLink',
        ),
    ]
